server:
  port: 8082
spring:
  application:
    name: order-web
  cloud:
    config:
      enabled: false
  main:
    allow-bean-definition-overriding: true  # 后来发现的bean会覆盖之前相同名称的bean
  # spring security basic认证账户，须全局配置一致
  security:
    user:
      name: ${SECURITY_USER_NAME:root}
      password: ${SECURITY_PASSWORD:root}
# eureka security
eureka:
  client:
    # client间隔多久去拉取服务注册信息，默认为30秒
    registry-fetch-interval-seconds: 20
    # eureka-server地址
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8100/eureka/
  instance:
    prefer-ip-address: true
    # eureka 界面显示的服务名称格式
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    # 表示eureka client发送心跳给server端的频率
    lease-renewal-interval-in-seconds: 1




